//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Operator_Aritmatika.layananOperator {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="aritmatikaSoap", Namespace="http://tempuri.org/")]
    public partial class aritmatika : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PenjumlahanOperationCompleted;
        
        private System.Threading.SendOrPostCallback PenguranganOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerkalianOperationCompleted;
        
        private System.Threading.SendOrPostCallback PembagianOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public aritmatika() {
            this.Url = global::Operator_Aritmatika.Properties.Settings.Default.Operator_Aritmatika_layananOperator_aritmatika;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PenjumlahanCompletedEventHandler PenjumlahanCompleted;
        
        /// <remarks/>
        public event PenguranganCompletedEventHandler PenguranganCompleted;
        
        /// <remarks/>
        public event PerkalianCompletedEventHandler PerkalianCompleted;
        
        /// <remarks/>
        public event PembagianCompletedEventHandler PembagianCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Penjumlahan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Penjumlahan(int a, int b) {
            object[] results = this.Invoke("Penjumlahan", new object[] {
                        a,
                        b});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void PenjumlahanAsync(int a, int b) {
            this.PenjumlahanAsync(a, b, null);
        }
        
        /// <remarks/>
        public void PenjumlahanAsync(int a, int b, object userState) {
            if ((this.PenjumlahanOperationCompleted == null)) {
                this.PenjumlahanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPenjumlahanOperationCompleted);
            }
            this.InvokeAsync("Penjumlahan", new object[] {
                        a,
                        b}, this.PenjumlahanOperationCompleted, userState);
        }
        
        private void OnPenjumlahanOperationCompleted(object arg) {
            if ((this.PenjumlahanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PenjumlahanCompleted(this, new PenjumlahanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pengurangan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float Pengurangan(float A, float B) {
            object[] results = this.Invoke("Pengurangan", new object[] {
                        A,
                        B});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void PenguranganAsync(float A, float B) {
            this.PenguranganAsync(A, B, null);
        }
        
        /// <remarks/>
        public void PenguranganAsync(float A, float B, object userState) {
            if ((this.PenguranganOperationCompleted == null)) {
                this.PenguranganOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPenguranganOperationCompleted);
            }
            this.InvokeAsync("Pengurangan", new object[] {
                        A,
                        B}, this.PenguranganOperationCompleted, userState);
        }
        
        private void OnPenguranganOperationCompleted(object arg) {
            if ((this.PenguranganCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PenguranganCompleted(this, new PenguranganCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Perkalian", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float Perkalian(float A, float B) {
            object[] results = this.Invoke("Perkalian", new object[] {
                        A,
                        B});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void PerkalianAsync(float A, float B) {
            this.PerkalianAsync(A, B, null);
        }
        
        /// <remarks/>
        public void PerkalianAsync(float A, float B, object userState) {
            if ((this.PerkalianOperationCompleted == null)) {
                this.PerkalianOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerkalianOperationCompleted);
            }
            this.InvokeAsync("Perkalian", new object[] {
                        A,
                        B}, this.PerkalianOperationCompleted, userState);
        }
        
        private void OnPerkalianOperationCompleted(object arg) {
            if ((this.PerkalianCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerkalianCompleted(this, new PerkalianCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pembagian", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float Pembagian(float A, float B) {
            object[] results = this.Invoke("Pembagian", new object[] {
                        A,
                        B});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public void PembagianAsync(float A, float B) {
            this.PembagianAsync(A, B, null);
        }
        
        /// <remarks/>
        public void PembagianAsync(float A, float B, object userState) {
            if ((this.PembagianOperationCompleted == null)) {
                this.PembagianOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPembagianOperationCompleted);
            }
            this.InvokeAsync("Pembagian", new object[] {
                        A,
                        B}, this.PembagianOperationCompleted, userState);
        }
        
        private void OnPembagianOperationCompleted(object arg) {
            if ((this.PembagianCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PembagianCompleted(this, new PembagianCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void PenjumlahanCompletedEventHandler(object sender, PenjumlahanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PenjumlahanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PenjumlahanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void PenguranganCompletedEventHandler(object sender, PenguranganCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PenguranganCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PenguranganCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void PerkalianCompletedEventHandler(object sender, PerkalianCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerkalianCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PerkalianCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void PembagianCompletedEventHandler(object sender, PembagianCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PembagianCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PembagianCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public float Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591